spring:
  datasource:
    name: d1
    url: jdbc:mysql://localhost:3306/ecom_Project?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 807385
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update

  main:
    allow-circular-references: true

product:
  path:
   images: src/products/images


